packages:
  - apps/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - unrs-resolver

publicHoistPattern:
  - esbuild
  - typescript
  - typegraphql-prisma
